import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder

# 1. Page Configuration (Must be the first Streamlit command)
st.set_page_config(page_title="Maharashtra Real Estate Predictor", page_icon="🏡", layout="wide")

# 2. App Header & Aesthetics
st.title("🏡 Maharashtra Real Estate Predictor")
st.markdown("Predict property prices across various districts in Maharashtra using a Random Forest Machine Learning model.")

# Display a high-quality house image from a free URL
st.image("https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?ixlib=rb-4.0.3&auto=format&fit=crop&w=1200&q=80", caption="Find Your Dream Home", use_container_width=True)

# 3. Model Training Function
@st.cache_resource
def train_model():
    df = pd.read_csv('maharashtra_houses.csv')
    
    # Encoding categorical data
    le_loc = LabelEncoder()
    df['location_encoded'] = le_loc.fit_transform(df['location'])
    
    le_furn = LabelEncoder()
    df['furnishing_encoded'] = le_furn.fit_transform(df['furnishing'])
    
    # Defining Features (X) and Target (y)
    X = df[['location_encoded', 'bhk', 'sqft', 'furnishing_encoded']]
    y = df['price_in_lakhs']
    
    # Initializing and training the Random Forest Model
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X, y)
    
    return model, le_loc, le_furn, df

model, le_loc, le_furn, df = train_model()

# 4. Sidebar for User Inputs (Creates a clean mobile menu)
st.sidebar.header("🏠 Enter Property Details")

selected_location = st.sidebar.selectbox("Select Location/District", df['location'].unique())
bhk_count = st.sidebar.number_input("Number of BHK", min_value=1, max_value=6, value=2)
sqft_area = st.sidebar.slider("Square Footage (Sq.Ft)", min_value=300, max_value=5000, value=1000, step=50)
furnishing_status = st.sidebar.selectbox("Furnishing Status", df['furnishing'].unique())

predict_button = st.sidebar.button("Predict Price")

# 5. Main Layout: Charts and Results
st.divider()
st.subheader("📊 Market Trends")
st.write("Average Property Prices by Location (in Lakhs)")

# Display a bar chart using Pandas and Streamlit
avg_price = df.groupby('location')['price_in_lakhs'].mean()
st.bar_chart(avg_price)

st.divider()
st.subheader("💡 Prediction Result")

# 6. Prediction Logic
if predict_button:
    # Transform user inputs to encoded values
    loc_encoded = le_loc.transform([selected_location])[0]
    furn_encoded = le_furn.transform([furnishing_status])[0]
    
    # Make prediction
    prediction = model.predict([[loc_encoded, bhk_count, sqft_area, furn_encoded]])
    
    # Display professional result
    st.success("Analysis Complete!")
    st.metric(label="Estimated Property Value", value=f"₹ {prediction[0]:.2f} Lakhs")
    st.info("Note: This valuation is generated by a Machine Learning algorithm and is based on sample market data.")
else:
    st.write("👈 Open the sidebar menu (top left arrow on mobile), enter your requirements, and click 'Predict Price'.")
